In [3]:
import numpy as np

## create arrays using numpy
## creating 1D array
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [5]:
arr2=np.array([1,2,3,4,5])
arr2.reshape([1,5]) #1 row nad 5 columns

array([[1, 2, 3, 4, 5]])

In [6]:
arr2=np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [7]:
## 2D array
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [11]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [14]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
## identity matrix 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
## attributes of numpy

arr =np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)

print("Shape:", arr.shape) # Output: (2, 3)

print("Number of dimensions:", arr.ndim) # Output: 2

print("Size (number of elements):", arr.size) # Output: 6

print("Data type:", arr.dtype) # Output: int64 (may vary based on platform)

print("Item size (in bytes):", arr.itemsize) # Output: 8 (may vary based on platform)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [17]:
## numpy vectorized operation

arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

## element wise addition,substraction,multiplication,division
print("addition:",arr1+arr2)
print("substraction:",arr1-arr2)
print("multiplication:",arr1*arr2)
print("division:",arr1/arr2)

addition: [11 22 33 44 55]
substraction: [ -9 -18 -27 -36 -45]
multiplication: [ 10  40  90 160 250]
division: [0.1 0.1 0.1 0.1 0.1]


In [18]:
## universal function
arr=np.array([2,3,4,5,6])
## square root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

##sign
print(np.sin(arr))

print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [3]:
## arry slicing and indexing operation

import numpy as np

arr=np.array([[1,2,3,4,],[5,6,7,8],[9,10,11,12]])
print("Array:\n",arr)

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [4]:
arr[0]

array([1, 2, 3, 4])

In [8]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [9]:
## modify array elments

arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [10]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [18]:
## statistical concepts--normalization
## to have a mean of 0 and statement deviation of 1

data = np.array([1, 2, 3, 4, 5])

# Calculate the mean and standard deviation

mean = np.mean(data)

std_dev = np.std(data)

# Normalize the data

normalized_data = (data -mean) / std_dev

print("Normalized data:", normalized_data)

# Output:

# Normalized data: [-1.26491106 -0.63245553 0. 0.63245553 1.26491106]


Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [19]:
# Mean

mean= np.mean(data)

print("Mean:", mean)

# Median

median= np.median(data)

print("Median:", median)

#Standard deviation

std_dev = np.std(data)

print("Standard Deviation:", std_dev)

# Variance

variance =np.var(data)

print("Variance:",variance)

Mean: 3.0
Median: 3.0
Standard Deviation: 1.4142135623730951
Variance: 2.0


In [16]:
## logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>5) & (data<=8)]

array([6, 7, 8])